#!/usr/bin/env python3
# SPDX-License-Identifier: CC-BY-NC-4.0
# Required Notice: Odradek - Auromix contributors (https://github.com/Auromix/odradek)
"""BRI01 candidate source contract. No supplier CAD is redistributed."""
from pathlib import Path
import json,csv,hashlib,math
D=Path(__file__).resolve().parent
for k in ['kicad','mechanical','previews','reports','fabrication']:(D/k).mkdir(exist_ok=True)
def save(n,x):(D/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
W='https://www.we-online.com/components/products/datasheet/'
P='https://www.phoenixcontact.com/'
sources=[dict(id='RJ',url=W+'615008160221.pdf',claim='Plain shielded 8P8C Cat6 THT jack; controlled body and drill drawing; no integrated magnetics. 1.5A is connector signal-contact rating.'),dict(id='RJ_CAD',url='https://www.we-online.com/components/products/download/Download_STEP_615008160221%20%28rev1%29.stp',claim='Private vendor STEP bounds include protruding EMI springs; cannot use nominal shell width alone.'),dict(id='RJ_FOOTPRINT',url='https://www.we-online.com/components/products/download/KiCad_WR-MJ%20%28rev26c%29.zip',claim='Private official library used to cross-check pin numbers and board-view orientation; original derived footprint is provided.'),dict(id='POWER',url=P+'en-us/products/pcb-header-pc-5-2-g-762-1720466',claim='PC5 two-pole header, 3 solder tails/pole,5mm tails,32A component rating; board current separately limited.'),dict(id='POWER_PLUG',url=P+'gb/products/1718481/pdf',claim='Click-and-Lock mating plug 23.24W x38.45L x19.8H mm; deenergized mating only.'),dict(id='STUD',url=W+'74651173.pdf',claim='7mm square M3 external stud; 4 THR tails on5.87mm square,1.85mm holes/3.2mm pads,0.5Nm max; PCB1.6..2mm. Datasheet contains wave-profile page but explicit warning says reflow only; process must resolve this.'),dict(id='COAX',url='https://www.amphenolrf.com/en-us/part/132170/7012/',claim='50ohm SMA jack-jack bulkhead,18GHz component specification; neither GMSL channel nor PoC validation.'),dict(id='COAX_DIM',url='https://www.amphenolrf.com/en-us/assets/file/4065861576/',claim='Manufacturer catalogue reference dimensions:22.1mm length;6.5mm bore with6mm flat;6.4mm maximum panel;fixedflangeAF9.5/removablenutAF8. Not a tolerance-controlled assembly model.'),dict(id='STACK',url='https://jlcpcb.com/impedance',claim='Candidate JLC04161H-7628:35um outer,210.4um PP,15.2um inner,1.065mm core, mirrored; PP Er4.4. Actual controlled stack and coupon required.' )]
sources.append(dict(id='POWER_DRAW',url='https://media.digikey.com/pdf/Data%20Sheets/Phoenix%20Contact%20PDFs/1720466.pdf',claim='Original Phoenix drawing mirrored by authorized distributor. Page4: rows from front19.80,22.34,27.42mm; three pins per pole. Explicit drawing audit, not generic family inference.'))
sources += [dict(id='COAX_OLD_DIM',url='https://www.farnell.com/datasheets/1681616.pdf',claim='Original Amphenol Connex catalogue printed p47 (2001), distributor-hosted:132170 nutAF8/fixedflangeAF9.5; longend->bearingface14.6,flangefarface16.3,total22.1; D-hole6.5 with overallflatheight6.0. Currentcontrolleddrawing still needed.'),dict(id='INTERNAL_PLUG',url='https://www.cinch.com/media/drawings/products/ethernet-usb/dr-stw-ss-37200-028-37200-032.pdf',claim='SS-37200-028 shieldedCat5e unbooted plug:total22.78REF,11.68wide,8.15high; AWG24..26,insulation0.94..1.07,cordOD<=5.97. No mateddatum to Wurth jack.'),dict(id='INTERNAL_CABLE',url='https://assets-cdn.helukabel.com/suppliers/Helukabel/documents/db/HELUKABEL_M800068_EN_GB.pdf',claim='HELUKABEL800068 AWG26/7 SF/UTP,insulationapprox0.95,OD5.5..5.9; fixedbend4D. Dimension-match candidate, termination/channel validation not completed.') ]
for s in sources:s['checked']='2026-09-30'
save('sources.json',sources)
C=[];pins=[]
def comp(ref,val,mpn,fp,u,v,rot,src):
 C.append(dict(ref=ref,value=val,MPN=mpn,footprint=fp,u_mm=u,v_mm=v,rotation_deg=rot,source_url=src))
def pin(ref,p,name,net):pins.append(dict(ref=ref,pin=str(p),name=name,net=net,role='passive'))
for ref,v,rot in [('J1',56,180),('J2',0,0)]:
 comp(ref,'SHIELDED_RJ45','615008160221','RJ45_615008160221',20,v,rot,W+'615008160221.pdf')
 for n in range(1,9):pin(ref,n,str(n),'ETH_'+str(n))
 for n in ['S1','S2']:pin(ref,n,'SHIELD','CHASSIS')
comp('J3','48V_EXTERNAL','1720466','PC5_2_762',96.5,56,180,sources[3]['url'])
pin('J3',1,'48V','VIN48');pin('J3',2,'RETURN','RETURN48')
for ref,u,net,val in [('J4',101,'VIN48','ARM_48V'),('J5',85,'RETURN48','ARM_RETURN'),('J6',46,'CHASSIS','CHASSIS_BOND')]:
 comp(ref,val,'74651173','THR_M3_74651173',u,12,0,W+'74651173.pdf');pin(ref,1,val,net)
for i,(u,v) in enumerate([(6,6),(110,6),(110,50),(6,50),(48,38),(68,38)],1):comp('H'+str(i),'M3_NPTH','PCB feature','M3',u,v,0,'original mechanical contract')
save('netlist.json',dict(revision='BRI01',components=C,pins=pins,nets=sorted(set(p['net']for p in pins))))
with(D/'bom.csv').open('w',newline='')as f:
 w=csv.DictWriter(f,fieldnames=['refs','qty','manufacturer','MPN','purpose','status','source_url']);w.writeheader()
 for refs,qty,mfr,mpn,purpose,source in [('J1 J2',2,'Wurth Elektronik','615008160221','shielded passive RJ45',sources[0]['url']),('J3',1,'Phoenix Contact','1720466','external48V PCB header',sources[3]['url']),('J4 J5 J6',3,'Wurth Elektronik','74651173','internal power and chassis studs',sources[5]['url']),('P3',1,'Phoenix Contact','1718481','external Click-and-Lock power mating plug',sources[4]['url']),('X1 X2',2,'Amphenol RF','132170','true coax feedthrough, mechanical bracket mount',sources[6]['url']),('P2',1,'Cinch Stewart','SS-37200-028','internal short unbooted RJ45 plug; crimp/compatibility qualification pending','https://www.cinch.com/products/ethernet-usb/plugs/ss-37200-028'),('W2',1,'HELUKABEL','800068','internal fixed Ethernet cable; cut length TBD','https://assets-cdn.helukabel.com/suppliers/Helukabel/documents/db/HELUKABEL_M800068_EN_GB.pdf'),('L4 L5 L6',3,'TE Connectivity','165295','M3 ringlug candidate only; exact barrel/centre datum and insulation/strainrelief pending','https://www.te.com/en/product-165295.html')]:w.writerow(dict(refs=refs,qty=qty,manufacturer=mfr,MPN=mpn,purpose=purpose,status=('candidate-mating-unverified'if refs in ['P2','W2','L4 L5 L6']else'selected-for-prototype-review; no inventory or manufacture release'),source_url=source))
with(D/'pin-net.csv').open('w',newline='')as f:
 w=csv.DictWriter(f,fieldnames=['ref','pin','name','net','role']);w.writeheader();w.writerows(pins)
# Small-signal estimate only; fab must calculate solder-mask model and coupon.
h=.2104;er=4.4;t=.035;wd=.24;gap=.20
z=87/math.sqrt(er+1.41)*math.log(5.98*h/(.8*wd+t));zd=2*z*(1-.48*math.exp(-.96*gap/h))
save('electrical-targets.json',dict(main_voltage_nominal_V=48,main_current_validation_target_cont_A=10,main_current_short_test_target_A=20,short_duration_s=None,not_certified_current=True,power_return_is_not_chassis=True,ethernet=dict(passive_pin_identity=list(range(1,9)),pairs=[[1,2],[3,6],[4,5],[7,8]],impedance_target_ohm=100,controlled_tolerance_percent=10,width_mm=wd,gap_mm=gap,preliminary_closed_form_no_mask_ohm=zd,model='IPC-style first-order coupled microstrip estimate only; not field solver or factory coupon',reference_planes='CHASSIS inner1/inner2 in EtherCAT region; no split under routed pair trunks'),gmsl=dict(route='50ohm coax adapters and matched cable assemblies only; no PCB signal trace',two_channels=True,PoC_and_6Gbps_validation=False)))
contract=dict(revision='BRI01',status='mechanical planning contract; final native footprint audit pending',units='mm',board=dict(size=[116,56,1.6],local_axes='u+x;v downward;z normal from PCB back toward components',assembly_transform='X=u-58; Y=z-27; Z=-9-v',holes=[dict(uv=[c['u_mm'],c['v_mm']],diameter=3.2,copper_keepout_radius=3.5,role='PCB chassis standoff'if int(c['ref'][1:])<=4 else'coax bracket M3')for c in C if c['ref'].startswith('H')]),ports=[dict(ref='J1',kind='RJ45 plain8P8C',axis_global=[0,0,-1],front_plane_global_Z=-65,centre_X=-38,cutout_global_xy=[-47.4,-26.0,-28.6,-8.6],cutout_kind='18.8x17.4 nominal rectangular planning opening incl.EMI springs, not vendor panel recommendation',plug_service_bbox_global=[[-50,-28,-105],[-26,-3.1,-65]],release_service_bbox_global=[[-53,-28,-105],[-23,-3.1,-65]],notes='Unshielded case walls must not prevent shield springs; tabs need actual panel compression design. Plug/boot PN and hand access unverified.'),dict(ref='X1',kind='SMA50ohmcoax',axis_global=[0,0,-1],axis_global_xy=[-10,-16],panel_global_Z=-65,cutout=dict(diameter=6.5,flat_width=6.0,max_panel_thickness=6.4),notes='Reference D-hole only in separate horizontal metallic ledge sharing PCB bracket bolts; not FR4 RF routing.'),dict(ref='X2',kind='SMA50ohmcoax',axis_global=[0,0,-1],axis_global_xy=[10,-16],panel_global_Z=-65,cutout=dict(diameter=6.5,flat_width=6.0,max_panel_thickness=6.4),notes='A/B identification mandatory; same gender two ports have no intrinsic channel coding.'),dict(ref='J3',kind='48Vpositive-lock2P',axis_global=[0,0,-1],front_plane_global_Z=-65,centre_X=38.5,cutout_global_xy=[28.9,-25.9,48.1,-10.6],plug_service_bbox_global=[[26.3,-26,-104],[50.7,-3.5,-65]],notes='19.2x15.3 header opening planning; mating plug reserved larger23.24x19.8. Actual overlap/datum pending source drawing. No live mating.')],internal=dict(RJ45=dict(ref='J2'),power=dict(refs=['J4','J5'],lug_centres_global=[[27,-21.9,-21],[43,-21.9,-21]],wire_direction=[0,0,1],max_lug_nut_height_above_PCB_top=12.0,notes='M3 eyelet+nut hardware and actual cableRmin TBD. Separate upstream fuse/limited source. Strain relief before wires leave removable core.')),requirements=['F-side complete package/mated envelope Y<-3mm','PCB mounts independent of cables,NPTH not electrical bond','externals unplug before lifting interface core','coax ledge carries coupling torque,FR4 not sole reaction','no new EtherCAT slave,PHY,magnetics or PoE on board'])
# Refined, source-bounded assembly datums. These are separate from nativeelectricalcheck.
contract['status']='native placement frozen; connector mated/cable validation explicitly partial'
for port in contract['ports']:
 if port['kind']=='SMA50ohmcoax':
  port['cutout']={'diameter':6.5,'overall_flat_to_opposite_arc':6.0,'flat_plane_from_axis':2.75,'max_panel_thickness':6.4,'normal':[0,0,-1],'flat_direction_global':'+X','provenance':'originalmaker2001catalogue; reference only'}
  port['body_axial_reference_global_Z']={'internal_end':-50.4,'fixed_shoulder_panel_bearing':-65,'fixed_shoulder_outside':-66.7,'external_end':-72.5}
  port['nut']={'removable_AF':8,'fixed_flange_AF':9.5,'nut_plus_washer_axial_planning':2.5,'not_controlled_nut_thickness':True}
  port['mating_SMA_male_cable_PN']=None
contract['internal']['RJ45']={'ref':'J2','axis':[0,0,1],'mouth_Z':-9,'candidate_plug':'Stewart SS-37200-028','candidate_cable':'HELUKABEL800068','plug_total_length_reference_mm':22.78,'plug_width_reference_mm':11.68,'plug_height_reference_mm':8.15,'actual_Wurth_mated_insertion_mm':None,'cable_OD_mm':[5.5,5.9],'fixed_Rmin_mm':23.6,'Rmin_basis':'4xlargestOD; manufacturer does not specify which radius convention in cited line','roof_inner_Z':39,'available_mouth_to_roof_mm':48,'conservative_height_formula_mm':'52.28 - actual_insertion_I + straight_exit_S; hereRtreatedasinnerradius andODadded','required_inequality_mm':'I-S >=4.28 before assemblytolerance','notes':'This is a measured-datum check still required, not 30mm whole-plug exposure; no boot. Match crimp tooling and shielding termination before prototype; fixed cable only.'}
contract['internal']['power']['lug_centres_global']=[[43,-21.9,-21],[27,-21.9,-21]]
contract['internal']['power']['ref_order']=['J4 VIN48','J5 RETURN48']
contract['board']['mechanical_parts_file']='mechanical/parts.json'
contract['assembly_limits']={'mount_to_table_edge_clearance_target_mm':2,'max_allowed_F_side_Y':-3,'external_plug_shape':'unfrozen; serviceboxes are conservative reservations, not supplierBREP','power_PLUG_nominal_mated_inference':'1718481 total38.45 and spigot14.7 suggest23.75 exposed if shoulder seatsflush; actual offset/engagement not guaranteed by standalone drawings','power_plug_full_dimensions_mm':[23.24,38.45,19.8]}
contract['internal']['power']['ring_lug_candidate']={'MPN':'TE165295','total_length_mm':14.35,'plate_thickness_mm':0.79,'hole_mm':3.2,'wire_mm2':[1.5,2.5],'controlled_hole_centre_to_wire_end':None,'barrel_outer_diameter':None,'assembly_BREP_status':'NOT included as a frozenpart; oldplannedlugnutbox does not close this candidate length','no_insulation_or_strain_relief':True}
save('connector-contract.json',contract)
print('BRI01 source',len(C),'footprints',len(pins),'logical pins')
