# SPDX-License-Identifier: CC-BY-NC-4.0
# Required Notice: Odradek - Auromix contributors (https://github.com/Auromix/odradek)
"""Generate host-independent, compile-checked FPL01_LOWER SPI example from one map.
Callbacks must be implemented for the chosen bench host; no hardware validation.
"""
import csv,json
from pathlib import Path
D=Path(__file__).resolve().parent
r=json.loads((D/'register-plan.json').read_text());pixels=list(csv.DictReader((D/'led-placement-reference.csv').open()))
lines=['/* SPDX-License-Identifier: CC-BY-NC-4.0 */','/* Auromix contributors. GENERATED by build_firmware_example.py. */','#include "fpl01_lower_example.h"','#include <string.h>', 'static const uint16_t dot_index[42] = {'+','.join(p['dot_index'] for p in pixels)+'};']
for i,op in enumerate(r['operations']):lines += [f'static const uint8_t op_{i}[] = {{'+','.join(str(v) for v in op['bytes'])+'};']
lines += ['static int write_read(const fpl01_lower_io *io, uint16_t addr, const uint8_t *p, size_t n) {','    uint8_t got[396];','    if (n > sizeof got || io->write_reg(addr,p,n)) return -1;','    if (io->read_reg(addr,got,n)) return -2;','    return memcmp(p,got,n) ? -3 : 0;','}', 'int fpl01_lower_init_dark(const fpl01_lower_io *io) {','    /* Caller applied VCC/VLED/VIO in reviewed order. Never drives SPI with VIO off. */','    io->vsync(0); io->delay_us(500);']
for i,op in enumerate(r['operations']):lines += [f'    if (write_read(io, {op["register"]}, op_{i}, sizeof op_{i})) return -{i+1};']
lines += ['    io->delay_us(100);','    io->vsync(1); io->delay_us(200); io->vsync(0);','    return 0;','}', 'int fpl01_lower_frame(const fpl01_lower_io *io, const uint16_t pixel[42], uint8_t master) {','    /* Chip stays at explicit 3 mA first-light setting; no automatic 20 mA enable. */','    uint8_t frame[396] = {0};','    for (size_t i=0;i<42;i++) {','        size_t a=2u*dot_index[i]; frame[a]=(uint8_t)pixel[i]; frame[a+1]=(uint8_t)(pixel[i]>>8);','    }','    io->vsync(0);','    if (io->write_reg(0x005,&master,1)) return -1;','    if (io->write_reg(0x200,frame,sizeof frame)) return -2;','    io->vsync(1); io->delay_us(200); io->vsync(0);','    return 0;','}', 'void fpl01_lower_spi_header(uint16_t a, int write, uint8_t h[2]) {','    /* Caller restricts a <= 0x3ff; callback owns SS and complete transaction. */','    h[0]=(uint8_t)(a>>2); h[1]=(uint8_t)(((a&3u)<<6)|(write?0x20:0));','}']
(D/'fpl01_lower_example.c').write_text('\n'.join(lines)+'\n')
(D/'fpl01_lower_example.h').write_text('''/* SPDX-License-Identifier: CC-BY-NC-4.0 */
/* Auromix contributors. Host-independent example, not executed on hardware. */
#ifndef FPL01_LOWER_EXAMPLE_H
#define FPL01_LOWER_EXAMPLE_H
#include <stdint.h>
#include <stddef.h>
typedef struct {
    /* Functions return 0 on success. SPI mode0, MSB-first, 100 kHz first light.
       Hold SS low across 2-byte address header plus payload; read timing follows
       TI SNVU786. Read-only/reserved addresses are never included by generator. */
    int (*write_reg)(uint16_t address,const uint8_t *data,size_t count);
    int (*read_reg)(uint16_t address,uint8_t *data,size_t count);
    void (*vsync)(int level);
    void (*delay_us)(uint32_t us);
} fpl01_lower_io;
int fpl01_lower_init_dark(const fpl01_lower_io *io);
int fpl01_lower_frame(const fpl01_lower_io *io,const uint16_t pixel[42],uint8_t master);
void fpl01_lower_spi_header(uint16_t address,int write,uint8_t header[2]);
#endif
''')
assert len({int(p['dot_index']) for p in pixels})==42
print('Generated FPL01_LOWER host-independent init/readback/frame example; not target firmware')
