#!/usr/bin/env python3
# SPDX-License-Identifier: CC-BY-NC-4.0
# Required Notice: Odradek - Auromix contributors (https://github.com/Auromix/odradek)
from pathlib import Path
from collections import Counter
import json,math
D=Path(__file__).resolve().parents[1];a=json.loads((D/'kicad/checks/native-audit.json').read_text());pts=[p['head_xy_mm'] for p in a['component_placement'] if p['ref'].startswith('D')]
def rectangle_gap(w,h):return min(math.hypot(max(abs(p[0]-q[0])-w,0),max(abs(p[1]-q[1])-h,0)) for i,p in enumerate(pts) for q in pts[i+1:])
j={'revision':'CD-PCB01','board_sha256':a['board_sha256'],'candidate_process':'6-layer 1mm;0.127 trace/clearance;0.40/0.20 through vias; source/process limits in fabrication-process-candidate.json','LED_geometry':{'count':285,'pitch_mm':2.8,'maximum_body_xy_mm':[1.7,.9],'max_body_to_max_body_mm':rectangle_gap(1.7,.9),'conservative_two_land_union_xy_mm':[2.4,.8],'inter_component_land_union_min_gap_mm':rectangle_gap(2.4,.8),'mask_expansion_per_side_mm':.05,'inter_component_mask_union_min_gap_mm':rectangle_gap(2.5,.9),'courtyard_xy_mm':[2.7,1.2],'min_courtyard_gap_mm':rectangle_gap(2.7,1.2),'assembler_accepted':False},'QFN_adjacent_pad':{'pitch_mm':.4,'land_width_mm':.2,'copper_gap_mm':.2,'soldermask_web_nominal_mm':.1,'web_process_colour_registration_TBD':True},'via_total':a['routing']['via_count'],'annulus_overlaps_SMD_land_count':len(a['via_solder_land_overlaps']),'annulus_overlap_types':dict(Counter('LP5860_EP' if any(o['ref'].startswith('U') for o in v['overlaps']) else 'passive_land' for v in a['via_solder_land_overlaps'])),'vias_with_drill_intersecting_SMD_copper':sum(any(o['drill_intersects_copper_land'] for o in v['overlaps']) for v in a['via_solder_land_overlaps']),'vias_with_drill_intersecting_SMD_mask':sum(any(o['drill_intersects_mask_opening'] for o in v['overlaps']) for v in a['via_solder_land_overlaps']),'LED_via_in_pad_count':sum(any(o['ref'].startswith('D') for o in v['overlaps']) for v in a['via_solder_land_overlaps']),'via_registry':a['via_solder_land_overlaps'],'required_process_review':'All19 annulus/SMD overlaps conservatively require resin filling+copper capping+planarity approval; native ordinary through-hole symbols and tenting alone do not express that operation. Remaining434 non-overlap through vias are not claimed to need VIP solely by this test. Manufacturer may choose global fill/cap. No plain soldermask plug substitution. Final paste, cap thickness, flatness, voiding, via tenting and panel assembly remain unapproved.','ground':{'In2_single_continuous_island':a['continuous_ground_reference_geometry'],'geometry_only':True},'electrical_trace_bound':a['routing']['net_statistics']['LED_POWER4'],'resistance_model':a['resistance_model'],'fabrication_release':False}
(D/'dfm-evidence.json').write_text(json.dumps(j,indent=2)+'\n');print('LED copper/mask/courtyard gaps',j['LED_geometry'],'VIP',j['annulus_overlap_types'])
