M48
; DRILL file KiCad 10.0.6 date 2026-09-30T18:56:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-30T18:56:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.180
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X13.15Y-7.06
X13.15Y-48.94
X26.85Y-7.06
X26.85Y-48.94
T2
X6.0Y-6.0
X6.0Y-50.0
X48.0Y-38.0
X68.0Y-38.0
X110.0Y-6.0
X110.0Y-50.0
M30
