#!/usr/bin/env python3
# SPDX-License-Identifier: CC-BY-NC-4.0
# Required Notice: Odradek — Auromix contributors (https://github.com/Auromix/odradek)
"""Original interface contract and BOM; catalogue dimensions are not vendor CAD."""
from pathlib import Path
import json,hashlib,csv
P=Path(__file__).resolve().parent; ROOT=P.parents[2]; WORK=ROOT.parents[1]/'work'
def save(path,x):path.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def h(p):
 if p.exists():return hashlib.sha256(p.read_bytes()).hexdigest()
 registry=ROOT/'docs/engineering/sources/r5-cam-hardware01.json'
 if registry.exists():
  for source in json.loads(registry.read_text())['sources']:
   if source.get('cache_path')==str(p.relative_to(ROOT.parents[1])):return source['sha256']
 raise FileNotFoundError('Reference cache absent and no prior source hash is registered: '+str(p))
cn='https://ikowb01.ikont.co.jp/technicalservice/download/pdf_catalog/1569CN.pdf'
en='https://ikont.com/api/directus-asset/e5d07c75-b960-4d38-99c0-e7a95f037172?modified_on=1775854492829'
skf='https://cdn.skfmediahub.skf.com/api/public/0901d196802809de/pdf_preview_medium/0901d196802809de_pdf_preview_medium.pdf'
sources=[dict(id='IKO-CURRENT',url=en,landing_page='https://ikont.com/products/rotary-motion/cam-followers',publisher='IKO',retrieved='2026-09-27',access='Read current official linked PDF using web tool; direct local request403; no local hash claimed',pages='PDF4–9,30 (printedI7–18,I59–60)',supports=['CFS4 dimensions and ratings match CN reference','CFS mounting, track, clearance, speed and supplied nut','stock eccentric family starts atOD16'],sha256=None),dict(id='IKO-CN',url=cn,publisher='IKO',retrieved='2026-09-27',cache_path='work/r5-cam-hardware01/iko1569cn.pdf',sha256=h(WORK/'r5-cam-hardware01/iko1569cn.pdf'),pages='PDF12–17 (printed21–32)',supports=['CFS4D8C5d4G M4x.7 G1=4 B7 B1=15 B2=8 C1=1 H1.5 f7.7 maxnutT.777Nm','C1120N C01120N maxstruct919N track799N at40HRC flat steel;4g reference','CFS3C0611N and structural484N comparison','class0 meanOD0/-8um,width0/-.120,radialrunout15um;radialinternal3..17um;mountH6/studh6','nut3.2 AF7 acrosscorners8.1ref;suppliednut no springwasher;holdhead and turnnut','caged grease d1n max84000 recommended8400','static highaccuracy factor3 and load factors: smooth1..1.2 normal1.2..1.5 shock1.5..3'],redistributed=False),dict(id='SKF-6078',url=skf,publisher='SKF',retrieved='2026-09-27',cache_path='work/gripper-support/skf.pdf',sha256=h(WORK/'gripper-support/skf.pdf'),pages='PDF264–265 / printed262–263',supports=['607/8-2Z8x19x6mm C2.34kN C0.95kN mass.0072kg reference85000 limiting43000rpm','same dimension619/8-2Z has C01/2aslarge(.465kN); cannot transfer ratings','607/8-2Z corresponding abutments da min10 max11,Da max17,ra max.3mm'],redistributed=False)]
save(ROOT/'docs/engineering/sources/r5-cam-hardware01.json',dict(revision='R5-CAM-HARDWARE01',license='CC-BY-NC-4.0 for original data organization; third-party source copyrights retained',sources=sources,inventory_or_price_verified=False,manufacturer_confirmation_received=False))
interface=dict(revision='R5-CAM-HARDWARE01',status='catalogue interface candidate; no vendor BREP, tolerance stack or carrier release',units='mm unless stated',source_ids=['IKO-CURRENT','IKO-CN','SKF-6078'],datum=dict(origin='fixed stud shoulder seated against rocker mounting plate',positive_u='along stud toward threaded tip; orthogonal radial coordinates v,w',head_transform=None),CFS4=dict(manufacturer='IKO',exact_designation='CFS4',variant='high-carbon-steel,caged,cylindrical outer ring,class0',dimensions=dict(D=8,C=5,d1=4,G='M4x0.7',G1=4,B=7,B1=15,B2=8,C1=1,H_hex=1.5,f_seat_min=7.7),nominal_axial_intervals=dict(front_assembly=[-7,0],rolling_outer_ring=[-6,-1],rolling_center=-3.5,plain_stud=[0,4],thread=[4,8]),tolerances=dict(mean_outer_D=[7.992,8],width_C=[4.880,5],radial_runout_max=.015,radial_internal_clearance=[.003,.017],stud_fit='h6',mounting_hole='4H6',mounting_hole_limits=[4,4.008],limits_note='mean D plus runout is not a max-material envelope; axial endpoints above nominal only'),ratings=dict(dynamic_C_N=1120,static_C0_N=1120,maximum_allowable_static_N=919,flat_40HRC_track_capacity_N=799,reference_body_mass_kg=.004,mass_excludes_supplied_nut=True,grease_recommended_relative_rpm=2100,grease_maximum_relative_rpm=21000,max_nut_torque_Nm=.777),supplied_nut=dict(thread='M4x0.7',thickness=3.2,across_flats=7,across_corners_reference=8.1,separate_SKU=None,lock_method='TBD; supplied nut not a verified locking system'),mounting_candidate=dict(rocker_plate_interval=[0,4],nut_interval=[4,7.2],nominal_tip_projection=.8,track_plate_interval=[-5.5,-1.5],effective_track_width=4,nominal_rolling_edge_allowance=.5,minimum_width_edge_allowance_if_centered=.44,plate_material_grade=None,plate_strength_verified=False,small_hole_chamfer='IKO general guidance C0.5 or less; actual micro seat to be designed',warning='four-mm seat places nut at nominal thread start; runout/chamfer/thread tolerance/tool clearance not closed')),
root_support_candidate=dict(manufacturer='SKF',exact_designation='607/8-2Z',quantity_per_petal=2,dimensions=dict(bore=8,outer_D=19,width=6),abutment=dict(shaft_shoulder_diameter_min=10,shaft_shoulder_diameter_max=11,housing_shoulder_opening_max=17,fillet_radius_max=.3,bearing_chamfer_min=.3,source='SKF-6078 matched row PDF264–265, printed262–263'),ratings=dict(C_N=2340,C0_N=950,reference_rpm=85000,limiting_rpm=43000,reference_mass_kg=.0072),interface='two separate coaxial short trunnions; no shaft through unchanged FORM02 root',trunnion_material_fit_retention=None,positive_torque_transfer=None,carrier_example=dict(bearing_center_y=[-16,16],bearing_intervals_y=[[-19,-13],[13,19]],candidate_housing_intervals_y=[[-19,-13],[13,19]],candidate_housing_OD=22,candidate_endcap_outer_D=20,candidate_endcap_intervals_y=[[-20,-19],[19,20]]),warning='housing and trunnions are custom candidates; bearing catalogue rating does not verify shaft, pin, bracket, retention or complete module'),package_example=dict(status='carrier-agent packaging counterexample under examination; not accepted arrangement',cam_center_y=32,stud_shoulder_y=28.5,stud_points_towards_negative_y=True,roller_y=[29.5,34.5],plain_stud_y=[24.5,28.5],nut_y=[21.3,24.5],stud_tip_y=20.5,track_plate_y=[30,34],housing_nearest_positive_y=20,nominal_tip_housing_axial_gap=.5),scope=['dimension and reaction inputs for R5-CARRIER01','no all-petal collision proof','no guarantee of 2kg gripping','groove8.05 candidate would alter STAGE01 placeholder, not silently update it'])
save(P/'mechanical-interface.json',interface)
rows=[
 ['CAM01',1,4,'IKO','CFS4','candidate','D8 C5 stud4h6 M4x.7; cylindrical caged class0',.004,cn,'Body mass only; track + shock + packing + lubrication + locking pending'],
 ['CAM02',1,4,'IKO','supplied M4 nut with CFS4; no separate PN','included-accessory','M4x.7 m3.2 AF7 e8.1 reference','',cn,'Do not double order; accessory mass and anti-loosening method TBD'],
 ['CAM03',2,8,'SKF','607/8-2Z','candidate','8x19x6 C2340 C0950N',.0072,skf,'Split trunnion fits/preload/retention and housing stiffness TBD'],
 ['CAM04',2,8,'custom','TBD split trunnion','TBD','8mm bearing interface; no throughshaft','','','Material/shoulder/fit/retention/positive torque connection not designed'],
 ['CAM05',1,4,'custom','TBD detachable rocker','TBD','a8 phase-45;4H6 shoulder seat minD7.7; candidate4mm seat','','','No3mm transverse pin selected; net section and torsion fatigue pending'],
 ['CAM06',1,4,'custom','TBD fixed cam track','TBD','candidate4mm axial contact width; groove8.05 candidate; steel40HRC reference','','','Material/heat treatment/finish/profile tolerances and assembly adjustability pending'],
 ['CAM07',1,4,'custom','TBD retainers and bracket fastener set','TBD','four existing root holes3.2; no new hole in frozen petal','','','Bolt and positive-torque load path depend on carrier CAD; no invented stock part'],
 ['CAM08',1,4,'TBD','TBD track lubrication and locking treatment','TBD','external rolling track; CFS pregreased internally with no refill hole','','','Compatibility/maintenance/contamination and no-loosening proof pending']]
with (P/'bom.csv').open('w',newline='') as f:
 w=csv.writer(f);w.writerow(['item','qty_per_petal','qty_four_petals','manufacturer','part_number','selection_status','specification','unit_reference_mass_kg','source_url','open_items']);w.writerows(rows)
print('interface, source register, and8BOMrows written')
