# SPDX-License-Identifier: CC-BY-NC-4.0
# Required Notice: Odradek — Auromix contributors (https://github.com/Auromix/odradek)
"""Derive a raised full-arm candidate from frozen reviewed artifacts.

Inputs stay immutable. --base-mesh is generated by export_integrated_arm_preview.py.
Private OEM CAD is used for discrete Boolean checks, never redistributed.
"""
from pathlib import Path
import argparse
import copy
import hashlib
import json

import cadquery as cq
import numpy as np

from build_layout import moved
from kinematics import Arm
from articulated_head_dynamics import ArticulatedHeadArm
from review_articulated_dynamics import numeric_jacobians, direct_body_effort
from screen_integrated_collisions import load_structure, load_head, pose_screen, transform_prefixes, box

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT/'engineering/generated/raised-arm-integration01'
RAISE = ROOT/'engineering/generated/shoulder-raise-01'
DZ = 35.


def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):return json.loads(Path(p).read_text())
def write(p, d):Path(p).write_text(json.dumps(d, indent=2)+'\n')


def sources_checked(d):
    for n, h in d.items():
        assert sha(ROOT/n) == h, ('source changed', n)


def derive_model(out):
    path = ROOT/'engineering/generated/articulated-dynamics-review/model.json'
    model = read(path); sources_checked(model['source_hashes'])
    sources = model['source_hashes']
    sources[str(path.relative_to(ROOT))] = sha(path)
    placement = read(RAISE/'part-placements.json')
    old_bodies = copy.deepcopy(model['arm']['bodies'])
    for j in model['arm']['joints'][1:]:
        j['origin_mm'][2] += DZ; j['origin_m'][2] += DZ*.001
    inst = placement['original_L12_instances']
    for b in model['arm']['bodies']:
        if b['id'] == 'J1_mass_proxy':continue
        if b['id'].startswith('L12_'):
            name = b['id'][4:]
            if name == 'hardware_reserve':
                metal = list(inst.values()); total = sum(x['mass_kg'] for x in metal)
                b['com_home_m'] = (sum(x['mass_kg']*np.array(x['com_world_m']) for x in metal)/total).tolist()
                b['input_boundary'] = '0.20kg old hardware reserve, relocated to new metal COM; old proxy inertia retained, not measured hardware'
            else:
                new = inst[name]
                b['mass_kg'] = new['mass_kg']; b['com_home_m'] = new['com_world_m']
                b['orientation_home'] = np.eye(3).tolist()
                b['inertia_com_kg_m2'] = new['inertia_about_COM_world_axes_kg_m2']
                b['source'] = 'SHOULDER-RAISE01 actual original nominal metal CAD integral in world axes'
        else:b['com_home_m'][2] += DZ*.001
    model['arm']['tool_home_transform'][2][3] += DZ*.001
    model['head_face_home_m'][2] += DZ*.001
    model['arm']['model_scope'].update(base='Fixed mounting base is excluded; fixed J1 module is included',
        object='2kg held rigid at derived home TCP949mm; contact loop not solved',
        shoulder='SHOULDER-RAISE01 nominal metal; 0.20kg hardware remains unmeasured reserve')
    model['limitations'] = model['arm']['model_scope']
    for p in [RAISE/'part-placements.json', RAISE/'geometry-decision.json', RAISE/'assembly-transform-contract.json']:
        sources[str(p.relative_to(ROOT))] = sha(p)
    model['revision'] = 'RAISED-ARM-INTEGRATION01'
    write(out/'model.json', model)
    return model, old_bodies


def check_model(model, out):
    m = ArticulatedHeadArm(model['arm'], model['head_bodies'], model['finger_joints'], model['head_face_home_m'])
    old = read(ROOT/'engineering/generated/articulated-dynamics-review/model.json')
    before = ArticulatedHeadArm(old['arm'], old['head_bodies'], old['finger_joints'], old['head_face_home_m'])
    trials = read(ROOT/'engineering/generated/articulated-dynamics-review/review.json')['trials']
    reports = []
    for r in trials:
        q = np.deg2rad(r['q_deg']); v = np.array(r['qd_rad_s']); a = np.array(r['qdd_rad_s2'])
        states = m.states(q); num = numeric_jacobians(m,q)
        jac = float(max(abs(b['J']-j).max() for b,j in zip(states,num))); assert jac<2e-8
        efforts = m.inverse_dynamics(q,v,a)
        direct = direct_body_effort(m,q,v,a,num,1e-4)
        err = float(abs(efforts-direct).max()); assert err<3e-4
        # Raising the entire chain above J2 along world Z leaves every J2..J7
        # lever arm and head mechanism unchanged, at any q1 about world Z.
        oldstates = {b['id']:b for b in before.states(q)}
        shift_errors=[]
        for b in states:
            if b['id'].startswith('L12_') or b['id']=='J1_mass_proxy':continue
            shift_errors.append(float(abs(b['p']-oldstates[b['id']]['p']-np.array([0,0,.035])).max()))
        assert max(shift_errors)<1e-12
        gravity_delta = m.gravity_compensation(q)-before.gravity_compensation(q)
        # J1 is vertical: additional shoulder material creates no J1 gravity
        # torque. No gravity qualification is inferred from this invariance.
        assert abs(gravity_delta).max()<1e-9
        eig=np.linalg.eigvalsh(m.mass_matrix(q)); assert eig.min()>0
        reports.append(dict(q_deg=r['q_deg'],max_jacobian_error=jac,max_direct_body_effort_error_Nm=err,
            max_downstream_world_translation_error_m=max(shift_errors),gravity_delta_Nm=gravity_delta.tolist(),
            min_mass_matrix_eigenvalue=float(eig.min()),inverse_dynamics_Nm=efforts.tolist()))
    total = sum(x['mass_kg'] for x in model['arm']['bodies'])+sum(x['mass_kg'] for x in model['head_bodies'])
    report=dict(revision=model['revision'],passed=True,trials=reports,
        modeled_mass_including_fixed_J1_and_2kg_object_kg=total,
        excludes='Fixed mounting base, unweighed head components and some detailed hardware; not complete machine mass',
        mathematical_states_only=True,manufacturing_release=False,model_sha256=sha(out/'model.json'),
        statement='Translation and gravity invariance plus independent pose-difference Jacobian and Newton/Euler checks; no torque/thermal/collision path qualification')
    write(out/'mathematics-review.json',report)
    return m


def prepare_mesh(basepath, target, model, out):
    data = read(basepath); sources_checked(data['source_hashes'])
    assert data['generator_sha256']==sha(ROOT/'engineering/export_integrated_arm_preview.py')
    inst = read(RAISE/'part-placements.json')['original_L12_instances']
    sources=data['source_hashes']
    for part in data['parts']:
        n=part['id']
        if n.startswith('L12_'):
            r=inst[n[4:]]; path=RAISE/r['file'];assert sha(path)==r['sha256']
            s=moved(cq.importers.importStep(str(path)).val(),np.array(r['T_world_from_part_mm']))
            assert s.isValid() and len(s.Solids())==1
            vv,tt=s.tessellate(.08,.10)
            part.update(vertices_m=[[c*.001 for c in v.toTuple()] for v in vv],triangles=tt,
                volume_mm3=s.Volume(),source=str(path.relative_to(ROOT)))
            sources[str(path.relative_to(ROOT))]=sha(path)
        elif not n.startswith(('BASE_', 'J1_CATALOG')):
            vv=np.asarray(part['vertices_m']); vv[:,2]+=.035;part['vertices_m']=vv.tolist()
    data['joints']=copy.deepcopy(model['arm']['joints'])
    data['head_face_world_mm']=(np.array(model['head_face_home_m'])*1000).tolist()
    arm=Arm(model['arm']); checks=[]
    for name,q in data['poses_deg'].items():
        pre=arm.prefixes(np.deg2rad(q))
        for part in data['parts']:
            if part['group'] not in ['arm_structure','head_fixed']:continue
            v=np.array(part['vertices_m'][0]);expected=(pre[part['attachment']]@np.r_[v,1])[:3]
            checks.append(dict(pose=name,part=part['id'],expected_vertex_world_m=expected.tolist()))
    data['arm_vertex_checks']=checks;data['revision']='RAISED-ARM-INTEGRATION01'
    data['scope']='Derived SHOULDER-RAISE01 full-arm geometry; J2 and downstream +35mm, actual longer L12 rear fork. Discrete geometry and mathematical checks only; not qualified hardware motion.'
    data['source_hashes'].update(model['source_hashes'])
    for p in [out/'model.json',ROOT/'engineering/export_integrated_arm_preview.py',ROOT/'engineering/integrate_raised_shoulder.py']:
        data['source_hashes'][str(p.relative_to(ROOT))]=sha(p)
    data['base_mesh_export_generator_sha256']=data['generator_sha256']
    data['generator_sha256']=sha(Path(__file__))
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(json.dumps(data,separators=(',',':'))+'\n')
    write(out/'assembly-parameters.json',dict(revision=data['revision'],joints=data['joints'],head_face_world_mm=data['head_face_world_mm'],
        tcp_home_mm=(np.array(model['arm']['tool_home_transform'])[:3,3]*1000).tolist(),poses_deg=data['poses_deg'],
        study_angles_not_control_limits=True,source_hashes=data['source_hashes'],original_mesh_part_count=len(data['parts']),
        source_head_revision='HEAD-INTEGRATED03 local geometry unchanged',manufacturing_release=False))
    print('Prepared raised mesh',len(data['parts']),flush=True)


def collision_screen(paths, out, model):
    p, structure, hashes, vendor=load_structure(paths)
    p['joints']=copy.deepcopy(model['arm']['joints'])
    shift=np.eye(4);shift[2,3]=DZ
    inst=read(RAISE/'part-placements.json')['original_L12_instances']
    for n,r in structure.items():
        if n.startswith('L12_'):
            entry=inst[n[4:]];path=RAISE/entry['file'];s=cq.importers.importStep(str(path)).val()
            r['shape']=moved(s,np.array(entry['T_world_from_part_mm']));r['source']=str(path.relative_to(ROOT))
            hashes[r['source']]=sha(path)
        elif not n.startswith('BASE_') and n!='J1':r['shape']=moved(r['shape'],shift)
    hashes.update(model['source_hashes'])
    poses=copy.deepcopy(p['poses_deg'])
    poses['shoulder_plus_90']=[0,90,0,0,0,0,0];poses['shoulder_minus_90']=[0,-90,0,0,0,0,0]
    result=dict(revision='RAISED-ARM-INTEGRATION01',poses={},source_sha256=hashes,vendor_sources=vendor,
        structure_part_count=len(structure),scope='Discrete actual BREP full-arm screening; arm/base fasteners are not included here, head hardware is included. Not a path or joint-domain certificate.',
        manufacturing_release=False,trajectory_qualified=False)
    for label in ['open','closed']:
        print('Import head',label,flush=True);head,h,qa=load_head(label);hashes.update(h)
        for r in head.values():r['shape']=moved(r['shape'],shift)
        for name,angles in poses.items():
            print('Screen',name,label,flush=True)
            check=pose_screen(p,structure,head,angles);result['poses'][name+'_'+label]=check
            print('=>',len(check['events']),'event pairs',flush=True)
            write(out/'collision-poses.json',result)
    # Exact mm-space prefix compared with independent SI exponential map.
    arm=Arm(model['arm']);rng=np.random.default_rng(3504);errors=[]
    for q in rng.uniform(-80,80,(16,7)):
        aa=transform_prefixes(p,q);bb=arm.prefixes(np.deg2rad(q))
        for a,b in zip(aa,bb):
            scale=b.copy();scale[:3,3]*=1000;errors.append(float(abs(a-scale).max()))
    assert max(errors)<1e-9
    result['independent_prefix_max_mm_error']=max(errors)
    result['generator_sha256']=sha(Path(__file__))
    write(out/'collision-poses.json',result)


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--base-mesh',type=Path,required=True)
    ap.add_argument('--mesh-output',type=Path,required=True)
    ap.add_argument('--out',type=Path,default=OUT)
    ap.add_argument('--model',action='append',default=[],metavar='ID=PATH')
    args=ap.parse_args();args.out.mkdir(parents=True,exist_ok=True)
    decision=read(RAISE/'geometry-decision.json');sources_checked(decision['source_hashes'])
    assert read(RAISE/'part-placements.json')['candidate_raise_mm']==DZ
    model,_=derive_model(args.out);check_model(model,args.out)
    prepare_mesh(args.base_mesh,args.mesh_output,model,args.out)
    if args.model:collision_screen({k:Path(v) for k,v in (s.split('=',1) for s in args.model)},args.out,model)
    sources_checked(model['source_hashes'])
    print('Finished derived candidate; original parameters unchanged',flush=True)


if __name__=='__main__':main()
