#!/usr/bin/env python3
# SPDX-License-Identifier: CC-BY-NC-4.0
# Required Notice: Odradek - Auromix contributors (https://github.com/Auromix/odradek)
"""Host-independent dual-driver SPI example, no target firmware or hardware test."""
from pathlib import Path
import csv,json
D=Path(__file__).resolve().parent
p=list(csv.DictReader((D/'pixel-map.csv').open()));r=[json.loads((D/f'register-plan-{g}.json').read_text()) for g in 'AB']
lines=['/* SPDX-License-Identifier: CC-BY-NC-4.0 */','/* Auromix contributors; generated by build_firmware.py; no hardware execution. */','#include "cd01_example.h"','#include <string.h>', 'static const uint16_t dot[285]={'+','.join(t['dot_index'] for t in p)+'};','static const uint8_t chip[285]={'+','.join('0' if t['driver']=='A' else '1' for t in p)+'};']
for d in range(2):
 for i,op in enumerate(r[d]['operations']):lines.append(f'static const uint8_t op_{d}_{i}[]={{'+','.join(str(v) for v in op['bytes'])+'};')
lines += ['static int write_read(const cd01_io *io,unsigned driver,uint16_t a,const uint8_t*p,size_t n){',' uint8_t got[396];if(n>sizeof got||io->write_reg(driver,a,p,n))return -1;',' if(io->read_reg(driver,a,got,n))return -2;return memcmp(p,got,n)?-3:0;','}', 'int cd01_init_dark(const cd01_io*io){',' /* Caller owns common VSYNC across all six head drivers; VIO valid, CS high first. */',' io->vsync(0);io->delay_us(500);']
for d in range(2):
 for i,op in enumerate(r[d]['operations']):lines.append(f' if(write_read(io,{d},{op["register"]},op_{d}_{i},sizeof op_{d}_{i}))return -{1+d*len(r[d]["operations"])+i};')
lines += [' io->delay_us(100);return 0;','}','int cd01_stage_frame(const cd01_io*io,const uint16_t pixels[285],uint8_t master){',' /* Does not pulse VSYNC. Caller keeps it low and coordinates all six drivers. */',' uint8_t frame[396];',' for(unsigned d=0;d<2;d++){','  memset(frame,0,sizeof frame);','  for(unsigned i=0;i<285;i++)if(chip[i]==d){unsigned a=2u*dot[i];frame[a]=(uint8_t)pixels[i];frame[a+1]=(uint8_t)(pixels[i]>>8);}','  if(io->write_reg(d,0x005,&master,1))return -1;','  if(io->write_reg(d,0x200,frame,sizeof frame))return -2;',' }',' return 0;','}','void cd01_commit_shared_vsync(const cd01_io*io){',' /* Global head scheduler only. After any stage failure do not commit stale/partial frames. */',' io->vsync(1);io->delay_us(200);io->vsync(0);','}','int cd01_spi_header(uint16_t a,int write,uint8_t h[2]){',' if(a>0x3ff)return -1;h[0]=(uint8_t)(a>>2);h[1]=(uint8_t)(((a&3u)<<6)|(write?0x20:0));return 0;','}']
(D/'cd01_example.c').write_text('\n'.join(lines)+'\n')
(D/'cd01_example.h').write_text('''/* SPDX-License-Identifier: CC-BY-NC-4.0 */
/* Auromix contributors. Host callbacks are not implemented here. */
#ifndef CD01_EXAMPLE_H
#define CD01_EXAMPLE_H
#include <stdint.h>
#include <stddef.h>
typedef struct {
 /* Driver0=J1pin7/U1; driver1=J1pin11/U2. Select exactly one. SPI mode0,
    MSBfirst,100kHz first-light,2MHz only after signal tests. Hold chip-select
    low across two-byte header and payload. Callbacks return0 on success.
    Caller checks pointers, power/VIO state, buffer lengths, bus exclusion. */
 int(*write_reg)(unsigned driver,uint16_t address,const uint8_t*data,size_t count);
 int(*read_reg)(unsigned driver,uint16_t address,uint8_t*data,size_t count);
 void(*vsync)(int level);
 void(*delay_us)(uint32_t us);
} cd01_io;
int cd01_init_dark(const cd01_io*io);
int cd01_stage_frame(const cd01_io*io,const uint16_t pixels[285],uint8_t master);
void cd01_commit_shared_vsync(const cd01_io*io);
int cd01_spi_header(uint16_t address,int write,uint8_t header[2]);
#endif
''')
print('Generated dual-driver C99 example, shared VSYNC commit separated')
